[package]
name = "example"
version = "0.1.0"
authors = ["HuXingYu <huxingyu@shimo.com>"]
edition = "2018"

[dependencies]

serialize_to_maps = { version = "0.1",  git = "https://github.com/huxy11/serialize_to_maps.git"}
